---
- hosts: "controller[0]"
  become: no

  tasks:
  - name: generate csr for admin
    delegate_to: 127.0.0.1
    template:
      src: admin-csr.json
      dest: "files/kubernetes"

  
  - name: generate certs for admin
    delegate_to: 127.0.0.1
    args:
     chdir: "files/kubernetes"
    shell: |
     cfssl gencert \
     -ca=kubernetes-ca.pem \
     -ca-key=kubernetes-ca-key.pem \
     -config=../ca-config.json \
     -profile=kubernetes \
     admin-csr.json | cfssljson -bare admin
 
  - name: generate kubeconfig for admin
    delegate_to: 127.0.0.1
    args:
     chdir: "files/kubernetes"
    shell: |
       kubectl config set-cluster {{clusterName}} \
         --insecure-skip-tls-verify=true \
         --server={{apiEndpointPublic}} \
         --kubeconfig=admin.kubeconfig \ 
       && \
       kubectl config set-credentials admin \
         --client-certificate=admin.pem \
         --client-key=admin-key.pem \
         --embed-certs=true \
         --kubeconfig=admin.kubeconfig \
       && \
       kubectl config set-context {{clusterName}} \
         --cluster={{clusterName}} \
         --user=admin \
         --kubeconfig=admin.kubeconfig \
       && \
       kubectl config use-context {{clusterName}} --kubeconfig=admin.kubeconfig 
