---
- name: create directories
  file: path={{item}} state=directory
  with_items:
  - "{{etcdHomeDir}}/ssl"

- name: "copy etcd ca cert"
  copy:
    src: "etcd/etcd-ca.pem"
    dest: "{{etcdHomeDir}}/ssl"
    mode: 400

- name: copy cert and key
  copy:
    src: "etcd/{{ansible_default_ipv4.address}}-{{item}}"
    dest: "{{etcdHomeDir}}/ssl/{{item}}"
    mode: 400
  with_items:
  - etcd.pem
  - etcd-key.pem

- name: download etcd and etcdctl binary 
  unarchive:
    src: https://github.com/coreos/etcd/releases/download/{{ etcdVersion }}/etcd-{{ etcdVersion }}-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: move etcd to /usr/local/bin
  copy:
    src: "/tmp/etcd-{{ etcdVersion }}-linux-amd64/{{item}}"
    dest: "/usr/local/bin/{{item}}"
    remote_src: yes
    mode: 0544
  with_items:
  - etcd
  - etcdctl

- name: create etcd systemd unit file
  template:
    src: secure-etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: 644
  register: etcd-systemd

- name: restart etcd
  systemd:
    name: etcd
    state: restarted
    daemon_reload: yes
